In [1]:
import numpy as np

list_ = [ "1" , "2" , "3" , "4" , "5" ]

array_list = np.array(object = list_)

Ans1

In [2]:
array_list.dtype

dtype('<U1')

Ans2

In [3]:
for i in list_:
    print(i)

1
2
3
4
5


In [4]:
for i in array_list:
    print(i)

1
2
3
4
5


Ans3

In [5]:
array_list = np.array(object = list_, dtype = int)

In [6]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Ans4

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [9]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


Ans5

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Ans6

In [11]:
my_identity_matrix = np.identity(5)
print(my_identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
